# Generated by Django 5.0.7 on 2024-09-08 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_billinginfo_shippinginfo_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shippinginfo',
            name='user',
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.cartorder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.cartorder'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
