# Generated by Django 5.0.7 on 2024-09-08 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_billinginfo_order_alter_shippinginfo_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='core.cartorder'),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='core.cartorder'),
        ),
    ]
